open https://www.mozilla.org/en-US/firefox/download/thanks/
open https://brew.sh/
open https://rustup.rs/
open https://ohmyz.sh/#install
open https://bitwarden.com/download/
open https://github.com/alacritty/alacritty/releases/
open https://apps.apple.com/us/app/magnet/id441258766
open https://discord.com/download
open https://www.around.co/
open https://www.microsoft.com/en-us/microsoft-teams/download-app
open https://apps.apple.com/app/slack/id803453959
open https://www.microsoft.com/en-us/microsoft-teams/download-app#desktopAppDownloadregion
open https://zoom.us/support/download?os=mac
